mysql:
  DRIVER: com.mysql.jdbc.Driver
  URL: localhost
  PORT: '3306'
  DATABASE: kalos?useSSL=false&characterEncoding=UTF-8&autoReconnect=true
  USER: kalos
  PASS: kalos
  GLAZED_PAY_DATA: ranks
  POKEMON_BAN_DATA: BanPokemonMap
  PREMIUM_DATA: premium_data
  PLAYER_EVENT_DATA: PlayerEventData
kimcore:
  SERVER_NAME: 'Kalos'
  SERVER_NAME_CN: '卡洛斯'
  SERVER_VAULT: '卡洛币'
  SERVER_POINTS: '卡点'
  SERVER_RMB: 'RMB'
  ARMOURERS_PATH: '/data/kalos/ArmourersData'
  SERVER_ADMIN_LIST:
    - Red_Carl
    - sulaoxian
BreedLimit:
  Ivs: 6
  Ability: false
  Pokemon:
    - Ditto
ItemBanList:
  - PIXELMON_CLONING_MACHINE
  - PIXELMON_RED_CHAIN
  - PIXELMON_AZURE_FLUTE
  - PIXELMON_GOLD_BOTTLE_CAP
  - PIXELMON_MINT_SEEDS
  - PIXELMON_WATERDUDE_WISHING_PIECE
  - PIXELMON_WISHING_PIECE
  - PIXELMON_BLACK_FLUTE
  - PIXELMON_WHITE_FLUTE
  - PIXELMON_DUSK_STONE_SWORD
  - PIXELMON_DUSK_STONE_HAMMER
  - PIXELMON_DUSK_STONE_AXE
  - PIXELMON_DUSK_STONE_HOE
  - PIXELMON_DUSK_STONE_PICKAXE
  - PIXELMON_DUSK_STONE_SHOVEL
  - PIXELMON_PURE_INCENSE
  - PIXELMON_INCENSE_BURNER
  - PIXELMON_ROCK_INCENSE
  - PIXELMON_ROSE_INCENSE
  - PIXELMON_FULL_INCENSE
  - PIXELMON_LAX_INCENSE
  - PIXELMON_LUCK_INCENSE
  - PIXELMON_ODD_INCENSE
  - PIXELMON_SEA_INCENSE
  - PIXELMON_WAVE_INCENSE
  - PIXELMON_REASSEMBLY_UNIT
  - PIXELMON_TIDAL_BELL
  - PIXELMON_CLEAR_BELL
  - PIXELMON_POKE_GIFT
  - PIXELMON_SILVER_BOTTLE_CAP
  - PIXELMON_CHISEL
  - PIXELMON_TRAINER_EDITOR
  - PIXELMON_PIXELMON_SPAWNER
  - PIXELMON_POKEMON_EDITOR
  - PIXELMON_DEN_SPAWNER
  - PIXELMON_WATERDUDE_WISHING_PIECE
  - PIXELMON_WISHING_PIECE
  - PIXELMON_RAINBOW_WING
  - PIXELMON_LURE_GROUND_WEAK
  - PIXELMON_LURE_POISON_WEAK
  - PIXELMON_LURE_ICE_WEAK
  - PIXELMON_LURE_GRASS_WEAK
  - PIXELMON_LURE_ELECTRIC_WEAK
  - PIXELMON_LURE_WATER_WEAK
  - PIXELMON_LURE_FIRE_WEAK
  - PIXELMON_LURE_NORMAL_WEAK
  - PIXELMON_LURE_FIGHTING_WEAK
  - PIXELMON_INCENSE_BURNER
  - PIXELMON_FULL_INCENSE
  - PIXELMON_LAX_INCENSE
  - PIXELMON_LUCK_INCENSE
  - PIXELMON_ODD_INCENSE
  - PIXELMON_PURE_INCENSE
  - PIXELMON_ROCK_INCENSE
  - PIXELMON_ROSE_INCENSE
  - PIXELMON_SEA_INCENSE
  - PIXELMON_WAVE_INCENSE
  - PIXELMON_LURE_FLYING_WEAK
  - PIXELMON_LURE_PSYCHIC_WEAK
  - PIXELMON_LURE_BUG_WEAK
  - PIXELMON_LURE_ROCK_WEAK
  - PIXELMON_LURE_GHOST_WEAK
  - PIXELMON_LURE_DRAGON_WEAK
  - PIXELMON_LURE_DARK_WEAK
  - PIXELMON_LURE_STEEL_WEAK
  - PIXELMON_LURE_FAIRY_WEAK
  - PIXELMON_LURE_FIGHTING_STRONG
  - PIXELMON_LURE_ICE_STRONG
  - PIXELMON_LURE_ELECTRIC_STRONG
  - PIXELMON_LURE_FIRE_STRONG
  - PIXELMON_LURE_NORMAL_STRONG
  - PIXELMON_LURE_HA_WEAK
  - PIXELMON_LURE_SHINY_WEAK
  - PIXELMON_LURE_WATER_STRONG
  - PIXELMON_LURE_GRASS_STRONG
  - PIXELMON_LURE_DARK_STRONG
  - PIXELMON_LURE_DRAGON_STRONG
  - PIXELMON_LURE_ROCK_STRONG
  - PIXELMON_LURE_PSYCHIC_STRONG
  - PIXELMON_LURE_GROUND_STRONG
  - PIXELMON_LURE_FLYING_STRONG
  - PIXELMON_LURE_POISON_STRONG
  - PIXELMON_LURE_BUG_STRONG
  - PIXELMON_LURE_GHOST_STRONG
  - PIXELMON_LURE_CASING_STRONG
  - PIXELMON_LURE_CASING_WEAK
  - PIXELMON_LURE_HA_STRONG
  - PIXELMON_LURE_SHINY_STRONG
  - PIXELMON_LURE_FAIRY_STRONG
  - PIXELMON_LURE_STEEL_STRONG
  - PIXELMON_PIXELMON_SPRITE
  - PIXELMON_ABILITY_PATCH
  - TCONSTRUCT_THROWBALL
  - TCONSTRUCT_SIGN_HEAD
  - TCONSTRUCT_PIGGYBACKPACK
  - PIXELMON_GRISEOUS_ORB
  - PIXELMON_ADAMANT_ORB
  - PIXELMON_LUSTROUS_ORB
  - PIXELMON_EARTH_PLATE
  - PIXELMON_DREAD_PLATE
  - PIXELMON_SPOOKY_PLATE
  - PIXELMON_IRON_PLATE
  - PIXELMON_FIST_PLATE
  - PIXELMON_ICICLE_PLATE
  - PIXELMON_DRACO_PLATE
  - PIXELMON_PIXIE_PLATE
  - PIXELMON_MEADOW_PLATE
  - PIXELMON_FLAME_PLATE
  - PIXELMON_SPLASH_PLATE
  - PIXELMON_SKY_PLATE
  - PIXELMON_INSECT_PLATE
  - PIXELMON_TOXIC_PLATE
  - PIXELMON_ZAP_PLATE
  - PIXELMON_MIND_PLATE
  - PIXELMON_STONE_PLATE