kimcore:
  SERVER_NAME: 'Kalos'
  SERVER_NAME_CN: '卡洛斯'
  SERVER_VAULT: '卡洛币'
  SERVER_POINTS: '卡点'
  SERVER_RMB: 'RMB'
  ARMOURERS_PATH: '/home/kalos/pokemon/ArmourersData'
  LEGENDARY_SPAWN: 10800
BreedLimit:
  Ivs: 6
  Ability: false
  Pokemon:
    - Ditto
ItemBanList:
    - PIXELMON_CLONING_MACHINE
    - PIXELMON_RED_CHAIN
    - PIXELMON_AZURE_FLUTE
    - PIXELMON_GOLD_BOTTLE_CAP
    - PIXELMON_MINT_SEEDS
    - PIXELMON_WATERDUDE_WISHING_PIECE
    - PIXELMON_WISHING_PIECE
    - PIXELMON_BLACK_FLUTE
    - PIXELMON_WHITE_FLUTE
    - PIXELMON_DUSK_STONE_SWORD
    - PIXELMON_DUSK_STONE_HAMMER
    - PIXELMON_DUSK_STONE_AXE
    - PIXELMON_DUSK_STONE_HOE
    - PIXELMON_DUSK_STONE_PICKAXE
    - PIXELMON_DUSK_STONE_SHOVEL
    - PIXELMON_PURE_INCENSE
    - PIXELMON_INCENSE_BURNER
    - PIXELMON_ROCK_INCENSE
    - PIXELMON_ROSE_INCENSE
    - PIXELMON_FULL_INCENSE
    - PIXELMON_LAX_INCENSE
    - PIXELMON_LUCK_INCENSE
    - PIXELMON_ODD_INCENSE
    - PIXELMON_SEA_INCENSE
    - PIXELMON_WAVE_INCENSE
    - PIXELMON_REASSEMBLY_UNIT
    - PIXELMON_TIDAL_BELL
    - PIXELMON_CLEAR_BELL
    - PIXELMON_POKE_GIFT
    - PIXELMON_SILVER_BOTTLE_CAP
    - PIXELMON_CHISEL
    - PIXELMON_TRAINER_EDITOR
    - PIXELMON_PIXELMON_SPAWNER
    - PIXELMON_POKEMON_EDITOR
    - PIXELMON_DEN_SPAWNER
    - PIXELMON_WATERDUDE_WISHING_PIECE
    - PIXELMON_WISHING_PIECE
    - PIXELMON_RAINBOW_WING
    - PIXELMON_LURE_GROUND_WEAK
    - PIXELMON_LURE_POISON_WEAK
    - PIXELMON_LURE_ICE_WEAK
    - PIXELMON_LURE_GRASS_WEAK
    - PIXELMON_LURE_ELECTRIC_WEAK
    - PIXELMON_LURE_WATER_WEAK
    - PIXELMON_LURE_FIRE_WEAK
    - PIXELMON_LURE_NORMAL_WEAK
    - PIXELMON_LURE_FIGHTING_WEAK
    - PIXELMON_INCENSE_BURNER
    - PIXELMON_FULL_INCENSE
    - PIXELMON_LAX_INCENSE
    - PIXELMON_LUCK_INCENSE
    - PIXELMON_ODD_INCENSE
    - PIXELMON_PURE_INCENSE
    - PIXELMON_ROCK_INCENSE
    - PIXELMON_ROSE_INCENSE
    - PIXELMON_SEA_INCENSE
    - PIXELMON_WAVE_INCENSE
    - PIXELMON_LURE_FLYING_WEAK
    - PIXELMON_LURE_PSYCHIC_WEAK
    - PIXELMON_LURE_BUG_WEAK
    - PIXELMON_LURE_ROCK_WEAK
    - PIXELMON_LURE_GHOST_WEAK
    - PIXELMON_LURE_DRAGON_WEAK
    - PIXELMON_LURE_DARK_WEAK
    - PIXELMON_LURE_STEEL_WEAK
    - PIXELMON_LURE_FAIRY_WEAK
    - PIXELMON_LURE_FIGHTING_STRONG
    - PIXELMON_LURE_ICE_STRONG
    - PIXELMON_LURE_ELECTRIC_STRONG
    - PIXELMON_LURE_FIRE_STRONG
    - PIXELMON_LURE_NORMAL_STRONG
    - PIXELMON_LURE_HA_WEAK
    - PIXELMON_LURE_SHINY_WEAK
    - PIXELMON_LURE_WATER_STRONG
    - PIXELMON_LURE_GRASS_STRONG
    - PIXELMON_LURE_DARK_STRONG
    - PIXELMON_LURE_DRAGON_STRONG
    - PIXELMON_LURE_ROCK_STRONG
    - PIXELMON_LURE_PSYCHIC_STRONG
    - PIXELMON_LURE_GROUND_STRONG
    - PIXELMON_LURE_FLYING_STRONG
    - PIXELMON_LURE_POISON_STRONG
    - PIXELMON_LURE_BUG_STRONG
    - PIXELMON_LURE_GHOST_STRONG
    - PIXELMON_LURE_CASING_STRONG
    - PIXELMON_LURE_CASING_WEAK
    - PIXELMON_LURE_HA_STRONG
    - PIXELMON_LURE_SHINY_STRONG
    - PIXELMON_LURE_FAIRY_STRONG
    - PIXELMON_LURE_STEEL_STRONG
    - PIXELMON_ABILITY_PATCH