main: red.kalos.core.Main
name: KalosCore
version: ${project.version}
depend: [Vault,ProtocolLib,PlayerPoints,CMI,PlotSquared,LuckPerms,DragonCore]
authors:
  - Red_Carl
website: "https://github.com/RedCarl/KalosCore"
commands:
  Core:
    aliases:
      - core
    description: "玩家管理系统。"
  Vote:
    aliases:
      - vote
    description: "赞助系统。"
  Group:
    aliases:
      - group
    description: "群组系统。"
  Rank:
    aliases:
      - rank
    description: "等级系统，特殊玩法。"
  Menu:
    aliases:
      - menu
    description: "主菜单，可通过蹲下+F打开菜单。"
  Kim:
    aliases:
      - kim
    description: "全球市场。"
  PokeAward:
    aliases:
      - pokeaward
    description: "宝可梦形态。"
  eb:
    aliases:
      - eb
    description: "宝可梦BUG，退出战斗。"